import type { Metadata } from "next";
import type { ReactElement } from "react";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SSO Provider",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): ReactElement {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white flex flex-col items-center justify-center h-screen">
          <h1 className="title">ETH-SSO</h1>
          {children}
        </div>
      </body>
    </html>
  );
}
